#作业3-8、3-9、3-10
wannted = ['A', 'X', 'C', 'P']
print(wannted)
print(sorted(wannted))
print(wannted)
print(sorted(wannted,reverse=True))
print(wannted)
wannted.reverse()
print(wannted)
wannted.reverse()
print(wannted)
wannted.sort()
print(wannted)
wannted.sort(reverse=True)
print(wannted)
print(len(wannted))
